version: 2.1

executors:
  honeybadger_ci:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest

jobs:
  static_analysis:
    executor: honeybadger_ci
    steps:
      - checkout
      - run:
          name: "Configure"
          command: |
            cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run:
          name: "Build"
          command: |
            cmake --build build
      - run:
          name: "Run test"
          command: |
            cd build
            ctest --no-compress-output -T Test --output-junit Testing/results.xml --rerun-failed --output-on-failure
      - run:
          name: "Run coverage report generation"
          command: |
            sh ./generate_gcov.sh
      - run:
          name: "Run sonar scanner"
          command: |
            sonar-scanner -Dsonar.login=$SONAR_TOKEN
      - store_test_results:
          path: build/Testing
      - store_artifacts:
          path: build/Testing

  build:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - checkout
      - attach_workspace:
          at: ~/honeybadger_ci
      - run:
          name: "Configure"
          command: |
            cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run:
          name: "Build"
          command: |
            cmake --build build
      - persist_to_workspace:
          root: ~/honeybadger_ci
          paths:
            - ./build
  test:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - checkout
      - attach_workspace:
          at: ~/honeybadger_ci
      - run:
          name: "Test"
          command: |
            cd build
            ctest --no-compress-output -T Test --output-junit Testing/results.xml --rerun-failed --output-on-failure
      - store_test_results:
          path: build/Testing
      - store_artifacts:
          path: build/Testing
      - persist_to_workspace:
          root: ~/honeybadger_ci
          paths:
            - build

  deploy:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - attach_workspace:
          at: ~/honeybadger_ci
      - run: |
          ls -la
          cd build
          ls -la
workflows:
  cicd:
    jobs:
      - static_analysis
      - build:
          requires:
            - static_analysis
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test