version: 2.1

jobs:
  build:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest
    steps:
      - checkout
      - run:
          name: "Configuration"
          command: |
            cmake --version
            cmake -Bbuild
      - run:
          name: "Say gcc"
          command: g++ --version
      - run: ninja --version
workflows:
  say-hello-workflow:
    jobs:
      - build
