version: 2.1

jobs:
  build:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest
    steps:
      - checkout
      - run:
          name: "CMake configure"
          command: |
            cmake -Bbuild -G Ninja
      - run:
          name: "CMake build"
          command: |
            cmake --build build
  test:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest
    steps:
      - checkout
      - run:
          name: "CTest"
          command: |
            cd build
            ctest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
