version: 2.1

executors:
  honeybadger_ci:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest
    working_directory: ~/honeybadger_ci

jobs:
  checkout:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - checkout

  build:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - run:
          name: "Configure"
          command: |
            ls -la
            cmake -Bbuild -G Ninja
      - run:
          name: "Build"
          command: |
            cmake --build build

  test:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - run:
          name: "Unit test"
          command: |
            ls -la
            cd build
            ctest
  deploy:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - run: ls -la
      - run: cmake --version

workflows:
  cicd:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test