version: 2.1

executors:
  honeybadger_ci:
    docker:
      - image: 0xd00d2bad/honeybadger_ci:latest
    working_directory: ~/honeybadger_ci

jobs:
  checkout:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - checkout
      - attach_workspace:
          at: ~/honeybadger_ci

  build:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - checkout
      - attach_workspace:
          at: ~/honeybadger_ci
      - run:
          name: "Configure"
          command: |
            ls -la
            cmake -Bbuild -G Ninja
      - run:
          name: "Build"
          command: |
            cmake --build build
      - persist_to_workspace:
          root: ~/honeybadger_ci
          paths:
            - ./build
  test:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - attach_workspace:
          at: ~/honeybadger_ci
      - run:
          name: "Create test directory"
          command: |
            ls -la
            cd build
            mkdir -p Test
      - run:
          name: "Execute Tests"
          command: |
            ls -la
            cd build
            ls -la
            ctest --no-compress-output -T Test || true
      - store_test_results:
          path: build/Test

  deploy:
    executor: honeybadger_ci
    working_directory: ~/honeybadger_ci
    steps:
      - attach_workspace:
          at: ~/honeybadger_ci/build
      - run: ls -la
      - run: cmake --version

workflows:
  cicd:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test