pipeline {
    agent {
         dockerfile {
            dir './.ci'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}