pipeline {
    agent {
         dockerfile {
            dir './.ci'
        }
    }
    stages {
        stage('test') {
            agent {
                docker {
                    image 'ubuntu:bionic'
                }
            }
            steps {
                sh 'lsb_release -a'
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'gcc:bullseye'
                }
            }
            steps {
                sh 'g++ --version'
                sh 'lsb_release -a'
            }
        }
    }
}