version: '3.8'
services:
  jenkins:
    container_name: jenkins_ocr_ci
    build: .
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/bin/docker:/usr/bin/docker
    